SHOUT_DURATION = 4.hours
NOTIFICATION_RADIUS = 1 #km
NOTIFICATION_DELAY = 1.day

ACCEPTED_APIS = [1,2]

MAX_USERNAME_LENGTH = 20
MIN_USERNAME_LENGTH = 6

SHOUT_COMPANY_NAME = "Street Shout Inc."
SHOUT_TRADEMARK_NAME = "Shout, Here & Now\u2122"
SHOUT_SHORT_NAME = "Shout"
SHOUT_SHORT_NAME_CAPITAL = "SHOUT"
SHOUT_POST_NAME = "shout"
SCORE_NAME = "karma"

CONTACT_EMAIL = "info@street-shout.com"
SENDER_EMAIL = SENDER_EMAIL_
FLAG_EMAIL = "info@street-shout.com"

APP_STORE_LINK = "http://itunes.apple.com/app/id734887535?mt=8"
ANDROID_STORE_LINK = ""

DELETE_ACCOUNT_LINK = "#" #todoBT delete account