SHOUT_DURATION = 4.hours
NOTIFICATION_RADIUS_1 = 0.1 #km
NOTIFICATION_RADIUS_2 = 1 #km
NOTIFICATION_RADIUS_3 = 10 #km

ACCEPTED_APIS = [1,2]

MAX_USERNAME_LENGTH = 20
MIN_USERNAME_LENGTH = 6

SHOUT_COMPANY_NAME = "Street Shout Inc."
SHOUT_TRADEMARK_NAME = "Shout, Here & Now\u2122"
SHOUT_SHORT_NAME = "Shout"
SHOUT_SHORT_NAME_CAPITAL = "SHOUT"
SHOUT_POST_NAME = "shout"
SCORE_NAME = "karma"

CONTACT_EMAIL = "info@street-shout.com"
SENDER_EMAIL = SENDER_EMAIL_
FLAG_EMAIL = "info@street-shout.com"

DELETE_ACCOUNT_LINK = "#" #todoBT delete account