# MySQL.  Versions 4.1 and 5.0 are recommended.
# 
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  reconnect: false
  database: snapbydevelopment
  pool: 5
  username: snapbydeveloper
  password: isthisit99
  socket: /tmp/mysql.sock


production:
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  reconnect: false
  database: snapby
  pool: 25
  username: snapbydeveloper
  password: isthisit99
  socket: /tmp/mysql.sock
